### ISSUE TITLE
[Stripe] Android compile error

### ISSUE THREAD

**Issue by Stanteq** [triniwiz/nativescript-plugins#104]
Hi. Please help with the following error on Android. I tried some suggestions from stackoverflow  by editing before-plugins.gradle but without any success, also I installed sdk  build-tools versions accordingly:     
```
android {
  project.ext {
    supportVersion = "29.+"
    androidXCore = "1.6.0"
    compileSdkVersion = 29
    targetSdkVersion = 29
    googlePlayServicesVersion = "16.+"
  }
}

```

Environment:
ns: 8

"@nativescript/core": "~8.1.5",
"@nativescript/android": "8.1.1",

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/x/.gradle/caches/transforms-2/files-2.1/bq191e62c435c2f5qd156e07a42ac8/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Failed to build plugin @triniwiz/nativescript-stripe :
Error: Command ./gradlew failed with exit code 1
```

**Comment by triniwiz** [comment]
I will add note but if you are not targeting API 31+ you should you v7 of the plugin

**Comment by Stanteq** [comment]
@triniwiz Thx for suggestion

Installed v.32 and I have same error.
Specified targeting version also in app.gradle & before-plugins.gradle files (tried various combinations)

api 31 never worked for me: `Installed Build Tools revision 31.0.0 is corrupted`

**Comment by triniwiz** [comment]
You will need to use the `alpha` version of the runtime along with the `next` version of the cli

**Comment by usmanumer009** [comment]
I am facing the same issue

**Comment by triniwiz** [comment]
@usmanumer009 you need to use the latest android runtime
