### ISSUE TITLE
NativeScript (Vue) 8 No such module 'Stripe' in Xcode

### ISSUE THREAD

**Issue by seivad** [triniwiz/nativescript-plugins#105]
I am receive the following error when trying to run the app in Xcode:

```No such module 'Stripe'```

Nativescript 8 using Vue and used ```ns plugin add @triniwiz/nativescript-stripe``` to pull it in. It compiles using the command line ```ns run ios --no-hmr``` but hitting the play button in Xcode breaks. 

It's coming from the Stripe class that's imported but doesn't exist, any ideas?

**Comment by tylerablake** [comment]
@seivad Try setting `IPHONEOS_DEPLOYMENT_TARGET = 11.0` in your `build.xcconfig`, that fixed it for me

**Comment by mreall** [comment]
@seivad Did setting `IPHONEOS_DEPLOYMENT_TARGET` work for you? I tried that and still have the same issue with the latest version.

**Comment by triniwiz** [comment]
Please ensure the `.xcworkspace` is opened and not `.xcodeproj `
