### ISSUE TITLE
[Couchbase] Cannot run on iOS simulator

### ISSUE THREAD

**Issue by CatchABus** [triniwiz/nativescript-plugins#106]
Every time I try to run my app in iOS simulator, I receive the following error for couchbase-lite:
```
building for iOS Simulator, but linking in dylib built for iOS, file '/Users/workpc/repo/clients/mobile/platforms/ios/Pods/CouchbaseLite/iOS/CouchbaseLite.framework/CouchbaseLite' for architecture arm64
```
which is strange because Couchbase indicates their binary contains slices for simulators too: https://docs.couchbase.com/couchbase-lite/current/objc/gs-prereqs.html

**Comment by NathanWalker** [comment]
@DimitrisRK Looks like the `3.0.0` cocoapod includes arm64 - can bump https://github.com/triniwiz/nativescript-plugins/blob/master/packages/nativescript-couchbase/platforms/ios/Podfile#L3 to `3.0.0` and remove the `platform` version directive there as not needed.

**Comment by prestopasto** [comment]
@NathanWalker I had this problem also and that fixed it.  Thank you!
