### ISSUE TITLE
[ffmpeg] incompatible `ffmpeg-kit-ios-full-gpl` version can be installed

### ISSUE THREAD

**Issue by gelzis** [triniwiz/nativescript-plugins#107]
Hi.

Latest versions of `ffmpeg-kit-ios-full-gpl` break the plugin (current Pod requirement allows it), [this commit](https://github.com/tanersener/ffmpeg-kit/commit/38d88e0c1219ecd67c6c9ced53427023ebc91c7e) renames the functions used by the plugin and when installing `4.5.1` it breaks.
`withExecuteCallback` => `withCompleteCallback`

I guess its needed to either make version requirement stricter that this new version doesn't get installed or release new version of the plugin that supports the newest dependency and renames the function usage.

Workaround for this currently is to pin `pod 'ffmpeg-kit-ios-full-gpl', '4.4.LTS'` into project own Podfile, it duplicates the plugin declaration, but installs the 4.4 version and plugin is usable.

**Comment by triniwiz** [comment]
fixed on the latest release
