### ISSUE TITLE
Imagezoom build issue

### ISSUE THREAD

**Issue by olsoluk** [triniwiz/nativescript-plugins#109]
In include.gradle of ImageZoom package, the PhotoView version does not seem to exist which is causing a build error in my project.

com.github.chrisbanes:PhotoView:565505d5c

Can this be updated, or is there a workaround?

**Comment by OPADA-Eng** [comment]
Same here

**Comment by wuilmerj24** [comment]
Fails with version of jp.wasabeef:glide-transformations

`A problem occurred configuring project ':app'.
Could not find jp.wasabeef:glide-transformations:4.1.0.
Required by:
    project :app
`

**Comment by OPADA-Eng** [comment]
can you please include these files:
- app.gradle 
- before-plugins.gradle

**Comment by OPADA-Eng** [comment]
@NathanWalker Have you published a new version on npm?

**Comment by NathanWalker** [comment]
I’ll check this tonight and ping back.

**Comment by NathanWalker** [comment]
@OPADA-Eng Looks like @triniwiz will need to publish the patch - will check with him on Monday about broadening the npm publish abilities on these packages.

**Comment by OPADA-Eng** [comment]
Thanks @NathanWalker

**Comment by NathanWalker** [comment]
@OPADA-Eng 4.1.2 is published now with that fix.
