### ISSUE TITLE
getDocument take longer for more records

### ISSUE THREAD

**Issue by PiyushHM** [triniwiz/nativescript-plugins#11]
const document = db.getDocument(documentId);

This call take almost 15 to 20 seconds for more than 1000 records.
Is there a better way to improve performance ?

**Comment by PiyushHM** [comment]
Please let us know by when we will get the fix ?

**Comment by PiyushHM** [comment]
let us know the workaround fix, if new version takes more time.

**Comment by triniwiz** [comment]
Can you try the latest version there was a couple updates
