### ISSUE TITLE
[couchbase] @triniwiz/nativescript-couchbase@1.3.1 missing native Android classes in NS7

### ISSUE THREAD

**Issue by agonper** [triniwiz/nativescript-plugins#111]
Hi @triniwiz, many thanks for these really nice plugins!

I've tried to install the latest version of the couchbase plugin, but I get this error on each operation
`java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics`

This does not happen with 1.2.5 though. Seems like some native files are missing 😢 

Thanks in advance!

**Comment by bunower** [comment]
I have the same error with NS-8 latest and couchbase latest

**Comment by agonper** [comment]
Hello @mamaly12. Did you try with NS CLI latest version (8.2.3)?

**Comment by mamaly12** [comment]
Hi @agonper,

After  I read your comment, I  installed the new version:
![image](https://user-images.githubusercontent.com/7683251/171942268-09a78569-f2b1-481c-95fb-329cfc13f80c.png)
 but it still gives the same error:
![image](https://user-images.githubusercontent.com/7683251/171942332-33a30a27-6a4f-489f-9241-ae2aeaf3e992.png)

**Comment by mamaly12** [comment]
Hi @agonper,
Thank you for your answer. After updating to the latest version, my problem is solved.
