### ISSUE TITLE
image-cache-it and pager require nativescript-permissions and date-fns

### ISSUE THREAD

**Issue by felixkrautschuk** [triniwiz/nativescript-plugins#123]
The plugins @nativescript/image-cache-it and @triniwiz/nativescript-pager both require _nativescript-permissions_ and _date-fns_, even though those dependencys are never used.

**Comment by triniwiz** [comment]
Seems like a packaging issue , will fix.

**Comment by NathanWalker** [comment]
image-cache-it should be fixed now - @triniwiz if you pull latest you can bump a patch for pager as well to close this.

**Comment by NathanWalker** [comment]
pager published with fix in 13.0.4 now as well.
