### ISSUE TITLE
CocoaPods could not find compatible versions for pod "CouchbaseLite"

### ISSUE THREAD

**Issue by PiyushHM** [triniwiz/nativescript-plugins#13]
getting error while building for iOS ...

[!] CocoaPods could not find compatible versions for pod "CouchbaseLite":
  In Podfile:
    CouchbaseLite (~> 2.8.1)

 

None of your spec sources contain a spec satisfying the dependency: `CouchbaseLite (~> 2.8.1)`.

 

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
'pod install' command failed.
For more information on resolving CocoaPod issues in NativeScript read.

The build works when changing version to 2.8.0 from '2.8.1' in node_modules/@triniwiz/nativescript-couchbase/platforms/iOS/Podfile

**Comment by triniwiz** [comment]
The fix is in the error  `out-of-date source repos which you can update with pod repo update or with pod install --repo-update`.
