### ISSUE TITLE
Stripe Implementation in NativeScript + Angular help

### ISSUE THREAD

**Issue by usmanumer009** [triniwiz/nativescript-plugins#150]
I want to implement stripe in NativeScript + Angular help needed. There is no proper documentation. I am learning nativescript

**Comment by micflan** [comment]
@usmanumer009 documentation is here: https://triniwiz.github.io/nativescript-plugins/api-reference/stripe.html

**Comment by usmanumer009** [comment]
@micflan do you have open source github repo related to stripe integration?

**Comment by triniwiz** [comment]
@usmanumer009 the source is located [here](https://github.com/triniwiz/nativescript-plugins/blob/master/docs/src/api-reference/stripe.md)
