### ISSUE TITLE
ERROR TypeError: Cannot read property 'setOnTouchListener' of null

### ISSUE THREAD

**Issue by earnestware** [triniwiz/nativescript-plugins#17]
Line 28: this._toast.getView().setOnTouchListener(new android.view.View.OnTouchListener({

Happens on android version==11

Robert

**Comment by triniwiz** [comment]
Released a `4.1.0` should fix u up for 11+

**Comment by earnestware** [comment]
perfect - didn't see the update 👍

**Comment by lostation** [comment]
Mmm I've also got this issue -> Cannot read property 'setOnTouchListener' of null ...recently.
I'm still using NS6... Is there a way to fix it without got to NS7...Thanks

**Comment by lostation** [comment]
Ah sh**** Android API level 30 causes the issue... https://www.py4u.net/discuss/626157
I've commented 'setOnTouchListener' method from toasty.android.js....and it's work again but as regular uncustomized toast...pfff thanks Android...normally it's IOS that is making me crazy...WHyyyyyyyyy you ? ;)
