### ISSUE TITLE
System.err: Calling js method onToastShown failed

### ISSUE THREAD

**Issue by earnestware** [triniwiz/nativescript-plugins#18]
just updated, was working w/iOS and switched back to Android - getting System.err: Calling js method onToastShown failed

"@triniwiz/nativescript-toasty": "^4.1.0",

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onToastShown failed
System.err: TypeError: _b.onShown is not a function
System.err: 
System.err: StackTrace:
System.err: onToastShown(file: node_modules/@triniwiz/nativescript-toasty/index.android.js:42:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.android.widget.Toast_Callback_vendor_144712_60_.onToastShown(Toast_Callback_vendor_144712_60_.java:17)

**Comment by earnestware** [comment]
it does show the toast message but then poof - crash

**Comment by felixkrautschuk** [comment]
I also have the same issue, but it seems to happen only on Android 11. On Android 10, I do not notice that issue.

**Comment by triniwiz** [comment]
ok fixed in `4.1.1` also @felixkrautschuk I left a note [here](https://triniwiz.github.io/nativescript-plugins/api-reference/toasty.html) , it's not supported unless an custom view is set which I haven't exposed an api for that atm

**Comment by felixkrautschuk** [comment]
Thank you @triniwiz for the very fast fix, now the Toast does not crash on Android 11 anymore

**Comment by earnestware** [comment]
so quick! thank you!!
