### ISSUE TITLE
[image-cache-it][IOS] slow app opening and slow navigation 

### ISSUE THREAD

**Issue by kefahB** [triniwiz/nativescript-plugins#182]
Hi @triniwiz 

I have 4 tabs, when I open the app to the default tab that has a cached image by the plugin the app icon animation is stoped a fractions of seconds and then It continue, then the naviation to the landing page is slowed down and the animation is with cuts...

When I change the tab where there is no cached img, the app icon animate as expected and the navigation also.

**Comment by triniwiz** [comment]
1. Platform
2. Image Source type
3. Image Dimensions
4. Have you tried the Core Image view ?

**Comment by kefahB** [comment]
I can confirm that it come from the image size, I have optimized all the images and it work as expected !

**Comment by triniwiz** [comment]
Have you tried setting a dimension on the image ?

**Comment by kefahB** [comment]
Actually no :/ I removed it
