### ISSUE TITLE
Toasty ios: ReferenceError: ToastStyle is not defined

### ISSUE THREAD

**Issue by felixkrautschuk** [triniwiz/nativescript-plugins#2]
First, thank you for keeping that bunch of plugins up-to-date and to support NS 7!

I tried @triniwiz/nativescript-toasty@4.0.3 and it works very well on Android (except Android 11, see https://github.com/triniwiz/nativescript-toasty/issues/45), but on iOS I do not see the Toast and I get the following error:

> ReferenceError: ToastStyle is not defined

**Comment by triniwiz** [comment]
Interesting did you try cleaning/nuking after installing? If yes can you try logging `ToastPosition` or `ToastStyle` you will need to declare it since the typings may not be available oob

**Comment by felixkrautschuk** [comment]
After installing the plugin, I cleaned the platforms folder and built the app again, but I get the same result.

Not sure what you mean, but this is what I do:

```
const toastModule = require("@triniwiz/nativescript-toasty");

exports.showToast = function(text, showLong) {
        try {
            console.log(toastModule.ToastDuration);
            console.log(toastModule.ToastPosition);

            const toasty = new toastModule.Toasty({
                text: text,
                duration: showLong === true ? toastModule.ToastDuration.LONG : toastModule.ToastDuration.SHORT,
                position: toastModule.ToastPosition.BOTTOM,
                textColor: "#FFFFFF",
                backgroundColor: "#656565",
                yAxisOffset: 20
            });

            toasty.show();
        } catch(e) {
            console.log(e);
        }
};
```

So I logged toastModule.ToastDuration and toastModule.ToastPosition, and I got:
CONSOLE LOG: {
"SHORT": "short",
"LONG": "long"
}
CONSOLE LOG: {
"BOTTOM": "bottom",
"BOTTOM_LEFT": "bottomLeft",
"BOTTOM_RIGHT": "bottomRight",
...
}

**Comment by triniwiz** [comment]
Sorry I meant doing something like the following 

```
console.dir(ToastStyle);
```

Usually if you were using something like typescript you would of need to add `declare const ToastStyle: any;`

**Comment by felixkrautschuk** [comment]
@triniwiz I gave it another try in a NS typescript project:

```
import {ToastDuration, ToastPosition, Toasty} from "@triniwiz/nativescript-toasty";

declare const ToastStyle: any;

export function showToast(text: string) {
    try {
        console.dir(ToastStyle);

        /*new Toasty({ text : text })
            .setToastDuration(ToastDuration.SHORT)
            .setToastPosition(ToastPosition.BOTTOM)
            .setTextColor("#FFFFFF")
            .setBackgroundColor("#656565")
            .show();*/
    } catch (e) {
        console.log("Error showToast:");
        console.log(e);
    }
}
```

So I tried to log the ToastStyle element and I got the same error

> ReferenceError: ToastStyle is not defined

**Comment by triniwiz** [comment]
Yeah seems to be a silly mistake 😂 with the project structure will publish soon

**Comment by triniwiz** [comment]
Update to the latest to enjoy 😄

**Comment by felixkrautschuk** [comment]
@triniwiz thanks you very much!
