### ISSUE TITLE
Upgrade Socket.IO 

### ISSUE THREAD

**Issue by triniwiz** [triniwiz/nativescript-plugins#20]
Support v3 of socket.io server

**Comment by Shidooo** [comment]
Do you have any news on progress? ☺️

**Comment by triniwiz** [comment]
[Yes](https://github.com/triniwiz/nativescript-plugins/blob/526227afb199a9e515246f3215e58a7219f312de/packages/nativescript-socketio/src-native/ios/TNSSocketIO/Podfile#L2) once I get some free time I’ll finish it

**Comment by Shidooo** [comment]
Great, good job 😄

**Comment by Shidooo** [comment]
Is a date known? In order to know if it is worth waiting a few days 😃 Thank you again for your work

**Comment by triniwiz** [comment]
done with https://github.com/triniwiz/nativescript-plugins/commit/2a7685e023e7971b15703ce5e0910a0a2bb84bda
