### ISSUE TITLE
TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by sivo1981** [triniwiz/nativescript-plugins#24]
√ Getting NativeScript components versions information...
√ Component nativescript has 7.1.2 version and is up to date.
√ Component @nativescript/core has 7.1.4 version and is up to date.
√ Component @nativescript/ios has ^7.1.1 version and is up to date.
√ Component @nativescript/android has 7.0.1 version and is up to date.

"@triniwiz/nativescript-toasty": "^4.1.1",

Error is thrown on Android 11. Line causing this issue in `index.android.js` at `38`
```
if (parseInt(Device.sdkVersion, 10) >= 30) {
    const callback = android.widget.Toast.Callback.extend({
        owner: null,
        onToastShown: function () {
            var _a, _b, _c, _d;
            this.super.onToastShown();
            (_d = (_c = (_b = (_a = this.owner) === null || _a === void 0 ? void 0 : _a.get()) === null || _b === void 0 ? void 0 : _b._androidOpts) === null || _c === void 0 ? void 0 : _c.onShown) === null || _d === void 0 ? void 0 : _d.call(_c);
        },
        onToastHidden: function () {
            var _a, _b, _c, _d;
            this.super.onToastHidden();
            (_d = (_c = (_b = (_a = this.owner) === null || _a === void 0 ? void 0 : _a.get()) === null || _b === void 0 ? void 0 : _b._androidOpts) === null || _c === void 0 ? void 0 : _c.onHidden) === null || _d === void 0 ? void 0 : _d.call(_c);
        }
    });
    const cb = new callback;
    cb.owner = ref;
    this._toast.addCallback(cb);
}

```

**Comment by sivo1981** [comment]
Setting compileSdkVersion 30 and targetSdkVersion 30 solves this issue.

**Comment by triniwiz** [comment]
Ok u can revert an try the latest version an lmk

**Comment by sivo1981** [comment]
Working in latest version. Really appreciate your work.

**Comment by sivo1981** [comment]
Lastest version not working on Android 6.

`Error: java.lang.ClassNotFoundException: android.widget.Toast$Callback`

**Comment by triniwiz** [comment]
All good to go in `4.1.3`
