### ISSUE TITLE
[Stripe - NS7 + Angular] CreditCardView contents undefined

### ISSUE THREAD

**Issue by salvatorebnt** [triniwiz/nativescript-plugins#26]
Here the minimal code:

**payment.component.html** 
`
<GridLayout rows="*,auto">
    <StackLayout row="0" width="350">
<CreditCardView #card/>
    </StackLayout>
  <GridLayout row="1" rows="*">
    <Button text="Create Token" (tap)="submitPayment(card)" class="btn btn-primary"></Button>
  </GridLayout>
</GridLayout>`
`<CreditCardView #card/>
`

**payment.component.ts** 

`
import { CreditCardView, CardParams, Address, Stripe } from '@triniwiz/nativescript-stripe';
export class PaymentComponent implements OnInit {

  @ViewChild('card') card : CreditCardView;
  constructor() {
  }

  submitPayment(cardView: CreditCardView): void {
    console.log(this.card.nativeView);
    console.log(cardView.cardParams);
  }
`

...and CreditCardViewModule imported in app.module.ts.

I correctly see the credit card form in the view but when i submit and I inspect the cardView parameter in submitPayment method, the content is all undefined...
What's the problem here?

Thanks in advance

**Comment by triniwiz** [comment]
Did u try passing it to the other stripe method instead logging ?

**Comment by salvatorebnt** [comment]
@triniwiz I don't see any other method to submit the data...or am I missing something maybe?

**Comment by salvatorebnt** [comment]
Not a issue... It works, just in debug mode the object cardParams looks like being undefined... but if it is passed to the method createCardToken it does its work
