### ISSUE TITLE
[Stripe - NS7 + Angular] CreditCardView - postal code

### ISSUE THREAD

**Issue by salvatorebnt** [triniwiz/nativescript-plugins#28]
Hello, i am using CreditCardView in my NS7 - Angular application, to catch the card info by the user:

<CreditCardView #card ></CreditCardView>

Here the result:

![image](https://user-images.githubusercontent.com/49240467/107130290-277c3280-68cc-11eb-9c71-de400a787ec3.png)

Is there any way to disable/hide the postal code input? Maybe setting some parameters in the view or in the typescript part?
If not, any workaround to hide that?

Thanks in advance

**Comment by triniwiz** [comment]
First grab the native instance from the view (.nativeView) now on iOS you can disable it with `.nativeView.postalCodeEntryEnabled  = false;` for android use `.nativeView.setPostalCodeRequired(false)`

**Comment by salvatorebnt** [comment]
Nativescript 7.1.0
Angular 11

I am not able to set that property:

**payment.component.html**
`
<CreditCardView id="card"></CreditCardView>
`

**payment.component.ts**
`
import { ChangeDetectorRef, Component, OnInit, ViewChild } from "@angular/core";
import { ActivatedRoute } from '@angular/router';
import { CardView } from "@nstudio/nativescript-cardview";
import { Stripe } from "@triniwiz/nativescript-stripe";
import { publishableKey } from "~/app/services/stripe.service";

@Component({
  selector: 'PaymentComponent',
  templateUrl: './payment.component.html'
})
export class PaymentComponent implements OnInit {
  private stripe: Stripe;
  @ViewChild("card", { static: true }) card: CardView;

  constructor(private route: ActivatedRoute, public changeDetectionRef: ChangeDetectorRef) {
    this.stripe = new Stripe(publishableKey);
  }

  ngOnInit() {
    if(isAndroid){
      this.card.nativeView.setPostalCodeRequired(false);
    }
  }
}
`

I don't see the method 'setPostalCodeRequired' anywhere in CardView model...
Can you help me where is the mistake?

Thanks @triniwiz for your work!

**Comment by triniwiz** [comment]
It’s there you’re just setting it too early the native view hasn’t even been created in onInit you should use the loaded callback on the view

**Comment by salvatorebnt** [comment]
What if I want completely hide that textField input?
Is that possible?

**Comment by triniwiz** [comment]
On iOS `postalCodeEntryEnabled` [should hide the field](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentCardTextField.swift#L317-L331) for android [API 21](https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/view/CardMultilineWidget.kt#L491-L499)+ use `setShouldShowPostalCode` and for [API 21](https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/view/CardInputWidget.kt#L339-L358) < `setPostalCodeEnabled` I'll add a new property for that in the next release

**Comment by triniwiz** [comment]
I added a new view property `showPostalCode` in the latest version
