### ISSUE TITLE
Error using latest version

### ISSUE THREAD

**Issue by NachmanRoss** [triniwiz/nativescript-plugins#29]
I just updated to @triniwiz/nativescript-stripe version nativescript-stripe@7.0.0-alpha6

When I ran ns build ios I get this error. I had to rollback to version nativescript-stripe@7.0.0-alpha5.

ERROR in payment/payment-page.ts:478:36
TS2352: Conversion of type 'ViewBase' to type 'CreditCardView' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'ViewBase' is missing the following properties from type 'CreditCardView': cardParams, showPostalCode, isUSZipRequired, borderColor, and 104 more.
    476 |     const paymentButton = <Button>args.object;
    477 |     paymentButton.visibility = "hidden";
  > 478 |     const ccView: CreditCardView = page.getViewById("card") as CreditCardView;
        |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    479 |     stripe.createCardToken(ccView.cardParams, (error, token) => {
    480 |       if (token && error === null) {
    481 |         tokenSource.set("token", formatToken(token));
Executing webpack failed with exit code 2.

**Comment by triniwiz** [comment]
Published a fix for that it was a typing issue
