### ISSUE TITLE
nativescript-stripe still broken

### ISSUE THREAD

**Issue by toby-wollit** [triniwiz/nativescript-plugins#3]
The nativescript-stripe plugin is still broken and missing some changes that I made to the @funder7 branch.

_getAuthenticationDelegate() is returning the incorrect delegate and CreditCardView get card() is missing a call to init().

Please see the following commits:

https://github.com/toby-wollit/nativescript-stripe/commit/863e48faf5291166886d5a0b46a7d7d69c8d1cd8
https://github.com/toby-wollit/nativescript-stripe/commit/a36e17a43b065083d1c855086af799a5df764e47

**Comment by triniwiz** [comment]
1. Nice catch on the delegate I think the moved some stuff in the latest version 
2. it's called [cardParams](https://github.com/triniwiz/nativescript-plugins/blob/master/packages/nativescript-stripe/index.ios.ts#L498) now

**Comment by funder7** [comment]
@triniwiz I just merged @toby-wollit 's PR, if you need to import those changes

**Comment by triniwiz** [comment]
@funder7 [added](https://github.com/triniwiz/nativescript-plugins/commit/23457fa4bf2562b210fd50210ae3d5c76bce4272) an [released](https://github.com/triniwiz/nativescript-plugins/releases/tag/7.0.0-alpha3-stripe)
