### ISSUE TITLE
[Stripe] No code or message in error when creating a payment method

### ISSUE THREAD

**Issue by sebj54** [triniwiz/nativescript-plugins#31]
Hi!

I identified a problem with the error returned by the `createPaymentMethod` method: there is no error code nor a message.

This line is causing the problem: https://github.com/triniwiz/nativescript-plugins/blob/2ece8face5325745e092bcdd8895b71a0aac7caa/packages/nativescript-stripe/index.android.ts#L674

You are trying to use `error.localizedDescription` which is not available. Here are the available properties:

![image](https://user-images.githubusercontent.com/5880435/107757706-30cf2a00-6d26-11eb-961e-f6ee402dc4df.png)

Maybe there are other errors concerned by this problem.

To reproduce the problem, you have to configure Stripe in live mode on your server and then use a test card (eg. 4242…). It took me a while to identify what was wrong in my app so I took the time to create that issue if it can help you to enhance the plugin.

PS: Is it normal that there is an alpha10 on npm and this repository only shows code for the alpha3?

**Comment by triniwiz** [comment]
updates are located [here](https://github.com/triniwiz/nativescript-plugins/pull/23) I'm currently trying to wrap up a couple things

**Comment by sebj54** [comment]
Thanks for the info!

**Comment by triniwiz** [comment]
published `7.0.0-alpha11` should help you out

**Comment by triniwiz** [comment]
closed with https://github.com/triniwiz/nativescript-plugins/commit/745a08711ae9fe1af3536a746b851e08440714a3
