### ISSUE TITLE
Cant find module

### ISSUE THREAD

**Issue by mxignas** [triniwiz/nativescript-plugins#32]
Hi, im trying to register a plugin in vue like this:

Vue.registerElement('YoutubePlayer', 
() => require('@triniwiz/nativescript-youtubeplayer').YoutubePlayer)
getting an error:

ERROR in ./app.js
Module not found: Error: Can't resolve '@triniwiz/nativescript-youtubeplayer'

what im doing wrong?

**Comment by triniwiz** [comment]
Seems like there was a build issue publishing a new build

**Comment by triniwiz** [comment]
Done `4.0.3` should be good to go

**Comment by triniwiz** [comment]
closed with https://github.com/triniwiz/nativescript-plugins/commit/745a08711ae9fe1af3536a746b851e08440714a3
