### ISSUE TITLE
Uncaught ReferenceError: ImageCacheItUtils is not defined ...

### ISSUE THREAD

**Issue by maddockst** [triniwiz/nativescript-plugins#33]
I'm trying to use `@triniwiz/nativescript-image-cache-it`. It works perfectly when using `tns run ios --no-hmr --bundle`, however after doing a `tns prepare ios --release` and changing the Scheme to `Release` inside of Xcode, I get the following error:

`ReferenceError: ImageCacheItUtils is not defined` ..

<img width="752" alt="Screenshot 2021-02-14 at 20 01 51" src="https://user-images.githubusercontent.com/14302328/107887653-7bf06500-6eff-11eb-86e6-20deb1c408ae.png">

I've tried removing + adding the plugin, `tns platform remove ios` / `tns platform add ios`, `tns clean` all to no avail. The app also works perfectly (in `Release` mode) if I build it without `@triniwiz/nativescript-image-cache-it`. 

Any thoughts on what this could be? 

package.json dependencies:

```
{
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "~7.1.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/theme": "~3.0.0",
    "@triniwiz/nativescript-image-cache-it": "^7.0.5",
    "@triniwiz/nativescript-stripe": "^7.0.0-alpha10",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "jwt-decode": "^3.1.2",
    "nativescript-ngx-shadow": "^6.5.0",
    "nativescript-ui-listview": "^9.1.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.3",
    "sass": "^1.32.4",
    "sharp": "^0.27.1",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/ios": "7.1.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~4.0.0",
    "@ngtools/webpack": "~11.0.0",
    "nativescript-dev-sass": "^1.7.0",
    "typescript": "~4.0.0"
  }
}
```

**Comment by maddockst** [comment]
Bump @triniwiz do you have any thoughts on what this could be please?

Thanks

**Comment by triniwiz** [comment]
I’ve only seen this if the project wasn’t built properly because it needs to build some swift code , you can try opening the project in Xcode clean an build from there .. LMK

**Comment by maddockst** [comment]
Many thanks for getting back to me.

I've cleaned the build folder through Xcode, rebuilt but the error still persists. This time however, the error occurs when running `tns run ios --no-hmr --bundle`. Heres a screenshot:

<img width="785" alt="Screenshot 2021-02-27 at 00 09 28" src="https://user-images.githubusercontent.com/14302328/109368191-35e8b900-7890-11eb-9c5e-8a2afb1a2af5.png">

**Comment by triniwiz** [comment]
If you tried w/o bundle also can you verify the existing of the plugin source in the Xcode project you’ll see mention of the plugin name

**Comment by maddockst** [comment]
Not sure if this is what you were talking about? This is all I'm seeing

<img width="635" alt="Screenshot 2021-02-27 at 00 20 24" src="https://user-images.githubusercontent.com/14302328/109368607-99bfb180-7891-11eb-82f6-1a731bcb73fd.png">

**Comment by triniwiz** [comment]
Yeah can check tnsnativesource

**Comment by maddockst** [comment]
That is empty
![Uploading Screenshot 2021-02-27 at 00.25.15.png…]()

**Comment by triniwiz** [comment]
Can you verify https://github.com/triniwiz/nativescript-plugins/tree/master/packages/nativescript-image-cache-it/platforms/ios/src that directory exists . A quick work around would be to create a similar arc directory in the app resource directory an copy those two files 🙂

**Comment by maddockst** [comment]
It does:

<img width="492" alt="Screenshot 2021-02-27 at 00 30 35" src="https://user-images.githubusercontent.com/14302328/109369066-02f3f480-7893-11eb-9795-1d90d285b3ac.png">

Does it have something to do with the folder not appearing in "Framework Search Paths"?

<img width="967" alt="Screenshot 2021-02-27 at 00 31 03" src="https://user-images.githubusercontent.com/14302328/109369089-143d0100-7893-11eb-884e-68e53267f1ad.png">

I'll try the copy for now :)

**Comment by triniwiz** [comment]
You can try moving the src contents up one directory so they live in the ios directory lmk if that helps

**Comment by maddockst** [comment]
<img width="497" alt="Screenshot 2021-02-27 at 00 38 11" src="https://user-images.githubusercontent.com/14302328/109369385-12c00880-7894-11eb-8681-a7d457bc1647.png">

I've tried that, but still the same 😞

**Comment by triniwiz** [comment]
Ok try copying those two files in `App_Resources/iOS/src`

**Comment by maddockst** [comment]
So, `tns run ios` now works 👌. But, doing a release build inside of Xcode still shows the same error ☹️

**Comment by maddockst** [comment]
<img width="253" alt="Screenshot 2021-02-27 at 01 02 29" src="https://user-images.githubusercontent.com/14302328/109370249-78fa5a80-7897-11eb-97fe-a205197d0019.png">

The two files have appeared in `TNSNativeSource` however

**Comment by triniwiz** [comment]
How are you building for release ?

**Comment by maddockst** [comment]
Well, I run this first:

`tns prepare ios --no-hmr --bundle --env.uglify --release`

And then inside of Xcode, I Build the current scheme (release) so I can test on a simulator

**Comment by triniwiz** [comment]
Can you try on a device ?

**Comment by maddockst** [comment]
I have just built and deployed on my iPhone X, and it still failed:

![Uploading Screenshot 2021-02-27 at 01.11.45.png…]()

**Comment by triniwiz** [comment]
What about `tns build ios —env.uglify —release` then try from Xcode

**Comment by maddockst** [comment]
Once I have done `tns build ios —env.uglify —release`, what should I do inside of Xcode? Won't the ▶️ icon do another build?

**Comment by triniwiz** [comment]
It should cache it still trying to figure out what’s causing this issue for u ... I might as well create a framework to prevent this in the future

**Comment by maddockst** [comment]
I did a `tns build ios —env.uglify — release` followed by `tns publish ios —ipa “”` and the app still failed to load on the device through TestFlight.

Really don’t get what’s happening, especially considering `tns run iOS` works perfectly.

**Comment by bbarne8** [comment]
@maddockst Did you ever solve this issue? I am currently experiencing the same thing and have not been able to make any progress.

**Comment by triniwiz** [comment]
Please ensure the `.xcworkspace` is opened and not `. xcodeproj `
