### ISSUE TITLE
Encountered different behavior between IOS and Android using the nativescript-couchbase plugin

### ISSUE THREAD

**Issue by sr3dna** [triniwiz/nativescript-plugins#38]
I am working on a nativescript angular project that makes use of Couchbase's Sync Gateway to synchronize documents so I need to be able to push documents to a listview whenever the database change listener receives callback messages.   

All is working fine on iOS, but on Android, I can only push items to the listview the first time.  If I navigate away from the component and relaunch it a second time, the listview item does not show up.   (`addDatabaseChangeListener` is called on init while `removeDataChangeListener` is called on component destroy) 

I don't know what I missed or did wrong.  I've tried manually calling listview's refresh;  adding 'setTimeout';  using the old version of the plugin (nativescript-couchbase-plugin) but I still couldn't get Android's version to work.

I created a bare minimal project to illustrate this issue.  Codes related to Replicator are omitted.  

https://github.com/sr3dna/cbplugintest/blob/master/src/app/home/test.component.ts

The following two screen captures show how iOS and Android behave differently.  

On iOS: 
![IOS](https://user-images.githubusercontent.com/15936818/109457220-4a06f480-7a0f-11eb-9eb3-67ca1062f701.gif)

On Android:
![Android2](https://user-images.githubusercontent.com/15936818/109457263-5e4af180-7a0f-11eb-8c80-5fc0ef8bf81d.gif)

Thanks in advance for any help on this issue.
Anders

**Comment by sr3dna** [comment]
@triniwiz, I tried tweaking the plugin codes a bit and found that the following changes solve this particular issue.   But to be honest, I don't know well enough why these changes would matter or even correct.  I also don't know if there would be any side effect.   I just want to let you know the result of my trial and error.    If you think these changes look ok, I can create a PR.

In `index.android.ts`:

![pluginchanges](https://user-images.githubusercontent.com/15936818/109565147-e6280e80-7a96-11eb-8960-1ca6325ad162.png)

**Comment by triniwiz** [comment]
Ah good catch I could of swore I saw the change listener was an interface

**Comment by triniwiz** [comment]
Should be good in `1.1.2`
