### ISSUE TITLE
Couchbase createDocument failed if input data contains an array

### ISSUE THREAD

**Issue by minhnhut** [triniwiz/nativescript-plugins#39]
Hi,
Thanks for great plugins. I am seeing bellow behavior:

Object -> cool
![image](https://user-images.githubusercontent.com/6104383/110191270-ce6fd200-7e6a-11eb-8fda-d71db5b902dc.png)

Array -> not cool
![image](https://user-images.githubusercontent.com/6104383/110191222-9c5e7000-7e6a-11eb-94d0-e2bebb329406.png)

I would like to store a list of photo along with my document. Is it expected that Array is not supported?

**Comment by triniwiz** [comment]
Nice catch seems like a serialize issue

**Comment by triniwiz** [comment]
Published a `1.2.1` with the fix

**Comment by minhnhut** [comment]
@triniwiz thanks for quick fix.
Is it published already?

Could you please point me to the commit that you made? I am reading your plugin's code, and curious about how you fix it.

**Comment by triniwiz** [comment]
It's published already the changes are [here](https://github.com/triniwiz/nativescript-plugins/pull/23/commits/97cc5c34d8177c56845168351e2683563cd60dc8#diff-937e88980220e9c0fe7ab55da40265a5c136c8e34bf2102b8cfce93f57386468)

**Comment by jamescodesthings** [comment]
Quick one here, the returned data type is not an array on the way back out (only checked android so far).

This has caused a bunch of array method errors for me on 1.2.1 android.

e.g:
```js
const db = new CouchBase('some-db');
const id = db.createDocument({
  class: 'a1',
  people: [{
    name: 'a',
  },
  {
    name: 'b',
  }],
})
console.log('result', db.getDocument(id));
```

This would log an object array:
```
{
  class: 'a1',
  people: {
    "0": {
      name: 'a',
    },
    "1": {
      name: 'b',
    },
  },
}
```

The error's I'm then getting are similar to `result.people.forEach is not a function`.

**Comment by triniwiz** [comment]
Interesting I get the following 
```ts
this.db = new CouchBase('tns-couchbase');
const id = this.db.createDocument({
		name: 'Osei',
		stuff: [{name:'ps'},{name:'xbox'},{name:'switch'},{name:'pc'}]
});
console.log(this.db.getDocument(id))
```

![image](https://user-images.githubusercontent.com/6695919/111133283-bc6bee80-8550-11eb-9c59-8f12cfa13e3b.png)

**Comment by jamescodesthings** [comment]
Cheers, will recheck.

**Comment by jamescodesthings** [comment]
My bad dude, problem was mine, relating to the workaround I'm using for https://github.com/triniwiz/nativescript-plugins/issues/40.

Cheers for the quick response.

**Comment by triniwiz** [comment]
Ah ok will try to fix that soon
