### ISSUE TITLE
[@triniwiz/nativescript-couchbase] crash when using regex comparision in a query

### ISSUE THREAD

**Issue by rayneram** [triniwiz/nativescript-plugins#46]
Nativescript version: 8.0.1
Plugin version: 1.2.3
Platform: android/ios

**Problem description:**
Plugin crashes with the following error on android when using a regex comparision in a query:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: JNI Exception occurred (SIGABRT).
System.err: =======
System.err: Check the 'adb logcat' for additional information about the error.
System.err: =======
System.err:
System.err:
System.err: StackTrace:
System.err: setComparison(file: app\webpack:\myapp\node_modules\@triniwiz\nativescript-couchbase\index.android.js:266:0)
System.err:     at query(file: app\webpack:\myapp\node_modules\@triniwiz\nativescript-couchbase\index.android.js:312:0)
```

**Observation:**
The problem appears to be with line 269 in `index.android.ts`:

`nativeQuery = com.couchbase.lite.Function.lower(item.property).regex(this.serializeExpression(item.value));`

If I replace this with the same syntax as the "like" comparison, then the crash doesn't happen:

`nativeQuery = com.couchbase.lite.Function.lower(com.couchbase.lite.Expression.property(item.property)).regex(this.serializeExpression(item.value));
`

Seems like it's maybe something to do with a missing call to Expression.property to wrap the item.property.

**ios:**
Similar code appears on line 585 of `index.ios.ts`. The crash error message on ios is slightly different, but is fixed by changing this line in the same way as above.

**Comment by triniwiz** [comment]
Fixed in `1.2.4`
