### ISSUE TITLE
NS7 - Stripe 7.0.0-alpha10

### ISSUE THREAD

**Issue by salvatorebnt** [triniwiz/nativescript-plugins#49]
Hello, i need to collect the "source" once the user insert the data in the cardView
The source I am talking is the one reported here:
https://stripe.com/docs/saving-cards#saving-credit-card-details-for-later
In that example i setted as tok_mastercard and it should be generated when the user inser the data in the view

Any chance to get this id in the current implementation?
Thanks in advance

**Comment by triniwiz** [comment]
I believe you can do that after creating a source from the card
