### ISSUE TITLE
[ socket.io-client-swift ] - pod install error

### ISSUE THREAD

**Issue by Ed-Simmons** [triniwiz/nativescript-plugins#51]
Hello, I'm getting the following error when trying to do a clean iOS build (NS 7, iOS runtime v6.5.4):

```
[!] CocoaPods could not find compatible versions for pod "Socket.IO-Client-Swift":
  In Podfile:
    Socket.IO-Client-Swift (from `https://github.com/triniwiz/socket.io-client-swift.git`)

Specs satisfying the `Socket.IO-Client-Swift (from `https://github.com/triniwiz/socket.io-client-swift.git`)` dependency were found, but they required a higher minimum deployment target.
```

Any thoughts on how to resolve this?

**Comment by Ed-Simmons** [comment]
I found a solution:

By including a `Podfile` in the `App_Resources/iOS` folder, you can force the target version to be higher than NativeScript's default of (I think) 8, like so:

```
platform :ios, '10.0'
```

Is this not a bit concerning for backwards compatibility though? Why was this necessary in the first place?

**Comment by triniwiz** [comment]
They bumped the [version](https://github.com/socketio/socket.io-client-swift/blob/master/Socket.IO-Client-Swift.podspec#L14)

**Comment by Ed-Simmons** [comment]
OK that makes sense! Interestingly I'm only getting this bug/ error message on a project that explicitly states a deployment target. If there is none given, the pod install has no errors.

**Comment by triniwiz** [comment]
I added the platform version to the plugin but are you still getting the following ?

```TS
TypeError: this.socket.connect is not a function
```

**Comment by Ed-Simmons** [comment]
I'm no longer getting that message :)
