### ISSUE TITLE
[@triniwiz/nativescript-image-cache-it] Images are blurry on iOS device

### ISSUE THREAD

**Issue by rayneram** [triniwiz/nativescript-plugins#54]
Nativescript version: 8.0.1
Plugin version: 7.0.5
Platform: ios
Device: iPhone 7+

**Problem description:**

Images displayed using the plugin on an iOS device appear at significantly lower quality than the same images displayed on an Android device or shown on iOS using a standard {N} Image tag.

I have the same code running on Android and iOS, with a set of full-width images pulled from a remote website, which are displayed using an ImageCacheIt tag with stretch=aspectFill. In each case, the images displayed on Android are pin-sharp, but on iOS they are noticeably soft (blurry). If I replace the ImageCacheIt tags with standard Image tags, the images are once again sharp on iOS.

**Observation:**

Line 336 of index.ios.ts seems to be where the resizing happens. If I debug the code at that point, I see (for my device):

this getMeasuredWidth() = 1242
Screen.mainScreen.scale = 3

Thus, the image width requested by the plugin is 1242/3 = 414

This seems like a low number for a retina screen with a 1080px width screen, and would maybe account for the low-res appearance.

If I change line 336 to this:

`ImageCacheItUtils.resizeImage(p1, this.getMeasuredWidth(), this.getMeasuredHeight(), resize, (resizedImage) => {`

(i.e. remove the divisions by Screen.mainScreen.scale, thus requesting a 1242 width image instead of a 414 width image) then the images in the App appear crisp and sharp again.

This feels like a hack and not a solution but may indicate why I'm seeing low-res blurry images with ImageCacheIt on the iOS retina screen.

**Comment by triniwiz** [comment]
Thanks I removed it in `7.0.6`
