### ISSUE TITLE
Feature Request(ImageCacheIt): Support Multiple Filter attributes

### ISSUE THREAD

**Issue by JacobFJ** [triniwiz/nativescript-plugins#66]
It seems {N} does not support filter css atribute. It is possible to parse multiple filter for example.

```
filter="sepia(.5) contrast(1.25) brightness(1.15) saturate(.9) hue-rotate(-2deg)"
```

Inspiration: [intagram.css filter mixture](https://picturepan2.github.io/instagram.css/)

**Comment by triniwiz** [comment]
Have you tried using it before ? [like](https://github.com/triniwiz/nativescript-plugins/blob/master/apps/demo/src/app.css#L21)
