### ISSUE TITLE
"Unknown error occurred,  try again later" when confirming the setupintent on nativescript-stripe plugin. 

### ISSUE THREAD

**Issue by harshakuk** [triniwiz/nativescript-plugins#73]
tried with both 7.0.0-beta-4 and 7.0.0-beta-3

using iOS 14.6

it works fine on android but not on iOS

//code snipet
stripe.CreateSetupIntent(this.paymentAccount).subscribe(
                (intent) => {
                    stripe.confirmSetupIntent(paymentMethodId, intent.clientSecret, (error: Error, setupIntent: StripeSetupIntent) => {
                        if (error) {
                            //handle error
                        }
}})

Doing something like this but the control is landing inside error of confirmSetupIntent and the error msg is quite vague.(unknown error, try again later)

Thanks in advance

**Comment by triniwiz** [comment]
Did you [add](https://github.com/triniwiz/nativescript-plugins/blob/master/apps/demo/src/app.ts#L12-L24) ?

**Comment by harshakuk** [comment]
> Did you [add](https://github.com/triniwiz/nativescript-plugins/blob/master/apps/demo/src/app.ts#L12-L24) ?

Yeah I did

@NativeClass()
    @ObjCClass(UIApplicationDelegate)
    class UIApplicationDelegateImpl extends UIResponder implements UIApplicationDelegate {
      applicationContinueUserActivityRestorationHandler(application: UIApplication, userActivity: NSUserActivity, restorationHandler: (p1: NSArray<UIUserActivityRestoring>) => void): boolean {
        console.log('applicationContinueUserActivityRestorationHandler');
        return handleContinueUserActivity(userActivity);
      }

      applicationOpenURLOptions(app: UIApplication, url: NSURL, options: NSDictionary<string, any>): boolean {
        console.log('applicationOpenURLOptions');
        return handleOpenURL(url);
      }

      applicationDidBecomeActive(application: UIApplication): void {
        // Get reference to the application window.
        //console.log("keyWindow: " + application.keyWindow);
        console.log('application active')
    }
    }

    Application.ios.delegate = UIApplicationDelegateImpl;

   I can't see the consoles inside ** applicationContinueUserActivityRestorationHandler** and ** applicationOpenURLOptions** printed while the console inside ** applicationDidBecomeActive** prints fine, so looks like its the correct place for the code. I tried using scenes too using this https://stackoverflow.com/questions/59029193/applicationopenurloptions-not-called-when-opening-app-from-share-sheet-of-anot but still the same error. 

Thanks in advance

**Comment by seivad** [comment]
Hey how do you impement this in NativeScript Vue? There isn't a good example and it throws an error when it has @nativeclass() etc... in the mounted() or even beforeMounted() methods.

**Comment by triniwiz** [comment]
@seivad can you try [this](https://v7.docs.nativescript.org/core-concepts/ios-runtime/how-to/objc-subclassing#calling-base-methods-Protocol) ?

**Comment by seivad** [comment]
I keep getting ```There was an unexpected error -- try again in a few seconds``` on iOS, setupIntent on that call is null but Android is all good, shows the pop-up window to authenticate. 

I've tried:

```app.ios.delegate = require('./CustomAppDelegate.ts').CustomAppDelegate```

and 

```
import * as utils from 'utils/utils'
import * as builder from 'ui/builder'
import * as app from 'application'
import { handleContinueUserActivity, handleOpenURL } from '@triniwiz/nativescript-stripe'

export class CustomAppDelegate extends UIResponder implements UIApplicationDelegate {
	applicationOpenURLOptions(application, url, options) {
		return handleOpenURL(url)
	}

	applicationContinueUserActivityRestorationHandler(application, userActivity, restorationHandler) {
		return handleContinueUserActivity(userActivity)
	}
}
```

But it didn't work, I don't understand where UIApplicationDelegate gets imported from, hence all the imports at the top hoping for the best. This stuff is really confusing / hard when you've never done any iOS development, I just want to be able to get the pop-up window working.

**Comment by triniwiz** [comment]
@seivad I recently found a solution to remove the need for the user to implement this

**Comment by seivad** [comment]
Okay, what version is that on? ^7.0.0-beta-4? I'm sure it worked at one point for me just doing ```StripeThreeDSUICustomization.init()``` in the mounted() function for my AddNewCard.vue component, any other ideas to get it going?

**Comment by triniwiz** [comment]
Not published yet but hoping to do it today

**Comment by seivad** [comment]
That would be amazing mate, if you can let me know what the package.json tag should be when it's ready. We are hoping to get our new app up this week for review. It's such a pain how this 3D Secure works these days, it's so much extra work server side as well to support it.

**Comment by seivad** [comment]
> Not published yet but hoping to do it today

hey any luck yet mate?

**Comment by seivad** [comment]
Hey any update on this yet? We got it to work using authenticatePaymentIntent() method and that does work with 3D Secure cards but now when trying to use the setup intents to store cards before use it continues to throw There was an unexpected error -- try again in a few seconds error again. The instructions are very clear to say what should be nested or not and I cannot figure out how to get setupIntents working when the user puts in a 3D Secure card to save for future use. Please advise

**Comment by harshakuk** [comment]
> Hey any update on this yet? We got it to work using authenticatePaymentIntent() method and that does work with 3D Secure cards but now when trying to use the setup intents to store cards before use it continues to throw There was an unexpected error -- try again in a few seconds error again. The instructions are very clear to say what should be nested or not and I cannot figure out how to get setupIntents working when the user puts in a 3D Secure card to save for future use. Please advise

Hi,
We were using modal for entering the card details. Unfortunately modals are unable to open the 3D secure link from iOS. We replaced modal with a page and that seemed to fix the issue. Hope it helps you in case you're using a modal too.
