### ISSUE TITLE
[ImageCacheIt] Pass headers when using `getItem` static method

### ISSUE THREAD

**Issue by williamjuan027** [triniwiz/nativescript-plugins#77]
When using `ImageCacheIt` in template, you could pass in a http header via the `headers` property (as specified in the [docs](https://triniwiz.github.io/nativescript-plugins/api-reference/image-cache-it.html#api)), like this:

```html
<ImageCacheIt 
        [headers]="headers"
        [src]="imageUrl"></ImageCacheIt>
```

Would it be possible to also pass in the `headers` property when using the `getItem` method to load images that require a header?

Perhaps something like this?

```typescript
ImageCacheIt.getItem(imageUrl, { headers: headers });
```

**Comment by triniwiz** [comment]
Yes this should be possible with a little change
