### ISSUE TITLE
Stripe Missing standard/index.d.ts in npm

### ISSUE THREAD

**Issue by justinkurtz** [triniwiz/nativescript-plugins#8]
Hi @triniwiz!

Thanks for all your hard work migrating these plugins! It think there's an issue with the npm packaging or the typescript compilation that causes a missing a file for nativescript-stripe plugin. 

Repro steps:

1. run `npm i @triniwiz/nativescript-stripe`
2. explore `.\node_modules\@triniwiz\nativescript-stripe\standard`

The index.d.ts file is missing that is present in the github repo. This forces you to import from either the ios.d.ts or the android.d.ts.

**Comment by triniwiz** [comment]
Nice find fix in the next release

**Comment by triniwiz** [comment]
fixed in `7.0.0-alpha4`

**Comment by luke-hawk** [comment]
Just updated to `7.0.0-alpha4` but the index.d.ts is still omitted in the standard folder

**Comment by triniwiz** [comment]
@luke-hawk seems like a build issue but I verified it for `7.0.0-alpha5`
