### ISSUE TITLE
App does not build for release iOS

### ISSUE THREAD

**Issue by OPADA-Eng** [triniwiz/nativescript-plugins#88]
Hi,
I'm trying to build the app for release it on Apple store using `ns build ios --release`
But I'm getting error message saying: 
```
ERROR in ./node_modules/@triniwiz/nativescript-image-zoom/index.ios.js + 1 modules
Cannot get final name for export '__esModule' of ./node_modules/@triniwiz/nativescript-image-zoom/index.ios.js
while generating the root export '__esModule' (used name: '__esModule')
Error: Cannot get final name for export '__esModule' of ./node_modules/@triniwiz/nativescript-image-zoom/index.ios.js
while generating the root export '__esModule' (used name: '__esModule')
```
I think the problem from the webpack because before I upgrade my app it was building successfully.
### Which platform(s) does your issue occur on?
- iOS
- iOS/Android :iOS 15, XCode 13

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.1.2
- Cross-platform modules: ~8.1.3
- Runtime(s): "@nativescript/ios": "8.1.0"
- Plugin(s): 
```
"dependencies": {
    "@codelab/nativescript-multi-select": "^2.0.1",
    "@mapo80/nativescript-range-seek-bar": "^1.0.3",
    "@nativescript-community/drawingpad": "^4.1.0",
    "@nativescript/animated-circle": "^1.1.7",
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/camera": "^5.0.9",
    "@nativescript/core": "~8.1.3",
    "@nativescript/datetimepicker": "^2.1.7",
    "@nativescript/directions": "^2.0.1",
    "@nativescript/fingerprint-auth": "^8.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/geolocation": "^7.2.1",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/picker": "^4.0.0",
    "@nativescript/social-share": "^2.0.4",
    "@nativescript/theme": "^3.0.1",
    "@nativescript/ui-charts": "^0.1.8",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@nstudio/nativescript-fancyalert": "^4.0.0",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
    "@nstudio/nativescript-loading-indicator": "^4.1.0",
    "@ticnat/nativescript-image-cache": "^1.0.1",
    "@ticnat/nativescript-intermec-printer": "^1.0.0",
    "@ticnat/nativescript-searchable-select": "^1.0.7",
    "@ticnat/nativescript-sewoo-printer": "^1.0.1",
    "@ticnat/nativescript-woosim-printer": "^1.0.0",
    "@triniwiz/nativescript-image-zoom": "^4.1.1",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "lodash": "^4.17.21",
    "md5": "^2.3.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "nativescript-audio": "^6.2.6",
    "nativescript-barcodescanner": "^4.1.2",
    "nativescript-carousel": "^7.0.1",
    "nativescript-dna-deviceinfo": "^3.7.1",
    "nativescript-drop-down": "^6.0.0",
    "nativescript-fonticon": "^2.0.2",
    "nativescript-google-maps-sdk": "file:nativescript-google-maps-sdk-4.0.1.tgz",
    "nativescript-handle-file": "^4.0.0",
    "nativescript-modal-datetimepicker": "^2.1.5",
    "nativescript-numeric-keyboard": "^5.0.2",
    "nativescript-permissions": "^1.3.11",
    "nativescript-phone": "^3.0.2",
    "nativescript-ripple": "^4.0.1",
    "nativescript-share-file": "^1.0.6",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-sqlite": "^2.8.5",
    "nativescript-ui-chart": "^9.0.0",
    "nativescript-ui-listview": "^10.0.0",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "pluralize": "^8.0.0",
    "timeago.js": "^3.0.2"
  },
  "devDependencies": {
    "@nativescript/android": "~8.1.1",
    "@nativescript/ios": "8.1.0",
    "@nativescript/types": "~8.1.0",
    "@nativescript/webpack": "~5.0.0",
    "@types/lodash": "^4.14.168",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-worker-loader": "^0.12.1",
    "typescript": "~4.3.5"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
1. create an app.
2. add the plugin.
3. try building for release.

### Is there any code involved? 
 No

**Comment by triniwiz** [comment]
Try adding the following to your tsconfig `"noEmitHelpers": false`

**Comment by OPADA-Eng** [comment]
@triniwiz that didn't work.

**Comment by OPADA-Eng** [comment]
I'm using this version of node and npm
$ node -v
v14.18.0
$ npm -v
7.24.1
I noticed that after installing the plugin I find this ad line 93:
Object.defineProperty(exports, "__esModule", { value: true });
removing it make me able to build

**Comment by OPADA-Eng** [comment]
Any news on fixing this?

**Comment by ChewingGlass** [comment]
This is happening for me in a completely unrelated project. Must be a webpack issue?

**Comment by ChewingGlass** [comment]
For me it seemed to happen because I was extending Error

**Comment by OPADA-Eng** [comment]
@ChewingGlass  I don't think it's a webpack issue, because it's happening just in release build.
The normal build does not through any error.

**Comment by ioanSflt** [comment]
Hello 👋 I came across the same issue in a Docusaurus project and I saw your open issue. 

 I think I partially solved it by using the `babel-plugin-add-module-exports` and `@babel/env` (I said partially, because at build it outputs this warning: `[WARNING] [object Object]`). More information [here](https://yarnpkg.com/package/babel-plugin-add-module-exports).

In `babel.config.js`:
```
{
  "presets": [["@babel/env", { "modules": "commonjs" }]],
  "plugins": ["add-module-exports"]
}
```

Hopefully this information will solve your issue or at least be useful for further investigations. ☺️

**Comment by brandonros** [comment]
I fixed it with this in my webpack config:

```
{
  optimization: {
    concatenateModules: false
  }
 }
```

**Comment by sepccom** [comment]
I'm getting the exact same issue as initially reported. Guess a more permanent solution hasn't been implemented yet.
@brandonros - I added the code you suggested but didn't work. Are you able to provide the full webpack.config.ts file so that I can compare to what I have - thanks
